### ISSUE TITLE
Wikipedia Alias' and Bigger Base Model for Training

### ISSUE THREAD

**Issue by lamberpj** [dell-research-harvard/linktransformer#13]
Dear LinkTransformer Team,

First off - congrats on a wonderful package.  I have three questions:

1) Are you able to make the underlying Wikipedia Alias' dataset available?  This looked non-trivial to scrape with the Wikimedia API, so would love to learn more about this effort!

2) Are there any plans to train a larger model with these aliases?  I would be very open to collaborate on this, as I think there may be a lot of room for improvement by shifting to a slightly larger model (or a huge model, that is then quantised heavily).  I think the current implementation provides a very robust linguistic measure of distance, but is still not quite there for true entity resolution based on aliases.

(PS: The canonical example I have in mind is "BofA" to "Bank of America".  I am sure this alias was in the training data, but the base model was a bit too parsimonious to keep this bridge).

3) Do you have any suggestions / thoughts on how best to use the OAI embeddings models for entity resolution (company names is my specific usecase).  My thinking is that appending something like "company name: XXXX" would help a lot for these general purpose embeddings models, but no doubt you have better insight here!

Kind regards,
Peter John Lambert (LSE Econ PhD Student)

**Comment by econabhishek** [comment]
Thanks, Peter! It appears that we never got notified of this issue via github notifications. 

1) We use wikidata (https://www.wikidata.org/wiki/Q487907) to train these models. We are currently working on an updated draft of the paper and will make the data in a couple of weeks. 
2) You can absolutely train a larger model on these! We already have code to do so in the repo, once the data is made available, perhaps you can train it with any backbone. We chose smaller models only to demonstrate trainability on free colab instances
3) While we haven't formally tested it, but there are references in the literature talking about problems BERT-based models face with short text, like names. You can absolutely use Open AI embeddings and see what you get! We have examples using OAI embeddings in the notebook. Re: the prefix, It is definitely worth trying out. I'd probably make it "The name of the company is XXXX" instead of the semi-colon format. If the motivation here is to add more language, it would be better achieved with a fuller sentence. Open AI has released two new embedding models as well, we will update their performance on our test split once we update the paper. We are aiming for a newer version of everything by late feb-early March. 

Sorry for the delay!

**Comment by lamberpj** [comment]
Thanks so much, really appreciate the detailed response.  I have been playing with FAISS a lot, inspired by your great package.

**Comment by econabhishek** [comment]
Hi @lamberpj , a new and vastly improved company model is now up. In fact, all of our models have been updated. We are targeting the completion of a new version of the paper + release of the data within the next week or so.

Closing this for now.
